name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2      
      - name: Build & test  
        run: make tests.docker
      - name: Upload coverage report
        uses: codecov/codecov-action@v1.0.2
        with:
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella
